---

  - name: Stop service cron on debian, if running
    ansible.builtin.systemd:
      name: bashible.timer bashible.service
      state: stopped

  - name: del bashible files
      ansible.builtin.shell: rm -rf /var/lib/bashible


