---

  - name: get_script
      raw: "kubectl -n d8-cloud-instance-manager get secret manual-bootstrap-for-worker -o json | jq '.data."bootstrap.sh"' -r"
    register: script

  - name: save
      copy:
        content="{{ config.stdout }}"
        dest="files/launch"
